[jordan]
keywords = ["jordan", "hmm-ok"]
content = """
hmm ok ðŸ¤” 

1. put a remote-controlled vibrator in her panties, so I give her tough time all night whilst im chilling at home.

2. I pull up undercover and chill outside inna car
"""

[mrs]
keywords = ["mrs", "modified-roblox-soccer"]
content = """
MRS is an association built off the roots of MPS and TPS old tools. MRS is based on the originally open sourced TPS legacy tools. Remade and modernized for competitive usage while also keeping authentic to what the game started as. 
â€¢ Founded February 2020
â€¢ Ownership transferred August 2020

Join [here](https://www.roblox.com/groups/5714572/MRS-Modified-Roblox-Soccer)
"""

[bug]
keywords = ["bug", "report", "bugs"]
content = """
Found a bug?
â€¢ If you are unsure, first discuss your bug in <#1023577224571523175> with the **Inquiry** tag
â€¢ Create a post on the same forum channel, but instead use the **Bug** tag
"""

[feature-request]
keywords = ["feature-request", "feature", "request", "feedback"]
content = """
Any idea what to add to mrs?
â€¢ If you think that your suggestion is already added, search your suggestion in <#1023577224571523175>
â€¢ Create a post on the same forum channel, but instead use the **Suggestion** tag
"""

[team-ownership]
keywords = ["team-ownership", "manage a team", "own-a-team", "manager"]
content = """
Want to own a team in mrs?
â€¢ Tell us the team you want
â€¢ Provide us a screenshot of your concept team. The minimum amount of players you must have is seven
â€¢ List any experience you have had as manager
"""

[group-request]
keywords = ["group-request", "join-group"]
content = """
Due to the large number of requests we get, it make take up to two weeks
"""

[group-rank]
keywords = ["group-rank", "promote-me"]
content = """
It may take up to a week for your rank on the group to change
"""

[verify-account]
keywords = ["verify", "register"]
content = """
Currently, we do not have a system in place in order to register your account.
We are trying to sort this ASAP, please bare with us.
"""
